config:
  backend_uri: "backend.minikube.local"
image:
  repository: mern-frontend
  tag: "1.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  host: frontend.minikube.local
