config:
  backend_uri: "localhost:3002"
image:
  repository: mern-frontend
  tag: "1.1"
replicaCount: 1
service:
  type: LoadBalancer
  port: 3000
ingress:
  enabled: false
  host: frontend.minikube.local
