version: "3"
services:
    mern-mongo:
        container_name: mern-mongo
        image: mongo
        volumes:
          - ./data:/data/db
        ports:
          - '27017:27017'
    mern-frontend:
        container_name: mern-frontend
        image: mern-frontend:1.0
        restart: always
        build: ./frontend
        ports:
          - "3000:3000"
    mern-backend:
        container_name: mern-backend
        image: mern-backend:1.0
        restart: always
        build: ./backend
        ports:
          - "3002:3002"