apiVersion: v1
kind: PersistentVolume
metadata:
  name: mern-mongo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.volume.storage }} 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /mnt/data/{{ .Release.Name }}
