apiVersion: v1
kind: Secret
metadata:
  name: mern-mongo-secret
data:
  mongodb-username: {{ .Values.secret.mongodb_username | b64enc | quote }}
  mongodb-password: {{ .Values.secret.mongodb_password | b64enc | quote }}
