apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mern-mongo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
