apiVersion: v1
kind: Secret
metadata:
  name: mern-backend-secret 
data:
  mongodb-uri: {{ with .Values.secret.mongodb_uri -}}
  # {{- list "mongodb://" .username ":" .password "@" $.Release.Name "-" .dbchart ":" .port "/" .dbconn | join ""  | b64enc |  quote }}
{{- end }}
