secret:
  mongodb_uri:
    username: your_db_username
    password: your_db_password
    dbchart: database
    dbport: 27017
    dbconn: "guestbook?authSource=admin"
image:
  repository: mern-backend
  tag: "1.1"
replicaCount: 1
service:
  type: LoadBalancer
  port: 3002
ingress:
  enabled: false
  host: backend.minikube.local
