apiVersion: v1
kind: Service
metadata:
  labels:
    name: mern-frontend-svc
  name: mern-frontend-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: mern-frontend
